import { Inter } from 'next/font/google'
import ChakraProviders from './providers'
import { Metadata } from 'next'
import ContainerWrapper from './container-wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Next.js site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProviders>
          <ContainerWrapper>{children}</ContainerWrapper>
        </ChakraProviders>
      </body>
    </html>
  )
}
