import { Inter } from 'next/font/google'
import ChakraProviders from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProviders>
          <nav>
            <h1>nav bar</h1>
          </nav>
          {children}
        </ChakraProviders>
      </body>
    </html>
  )
}
